- MessageSigning.md
Might as well save others the debug time since it's hard to see at first glance.
> Fixed typo in MessageSigning.md example

- src/api/util.js
I made a mistake in my last PR, https://github.com/Berry-Pool/nami-wallet/pull/129 I didn’t await for the .json() call on the response.
> The JSON method should be awaited

- src/api/extension/index.js
I had attempted to send an NFT from my wallet using the recipient wallet's $handle. Instead of going to the wallet that owns the $handle, the NFT was sent to the adahandle team's wallet that holds a special "empty" handle ([link](https://cardanoscan.io/token/f0ff48bbb7bbe9d59a40f1ce90e9e9d0ff5002ec48f232b49ca0fb9a?address=addr1qye59j5vquaprdmxf0gs2y3n20necqg3dnzxty23x07u7awkchm0w43pg2uczh4vcvdr59teny2996rq4tmq2umjyqvqlhm7d2)).
It appears as if just the adahandle policy is sent to the blockfrost api, it returns the address of the "empty" handle. For example,
```javascript
blockfrostRequest(`/assets/${policy}/addresses`) // only sending policy
>>> 'addr1qye59j5vquaprdmxf0gs2y3n20necqg3dnzxty23x07u7awkchm0w43pg2uczh4vcvdr59teny2996rq4tmq2umjyqvqlhm7d2'
```
This suggests that `assetName` was …
> Added check on empty assetName

- jest.config.js
- src/api/messaging.js
- src/api/webpage/eventRegistring.js
- src/api/webpage/index.js
- src/pages/Content/injected.js
- src/test/unit/api/webpage/eventRegistring.test.js
- src/ui/app/components/transactionBuilder.jsx
While following the thread https://github.com/cardano-foundation/CIPs/pull/151 I noticed some work was done very recently to support the on() proposal. I also notice a couple of issues with it, being 1) using `.name` of the callback to identify which to clear out and 2) Support to remove the callback was removed, while a lonely `removeListener` function was left
- Added `off` method, based on `removeListener`
- Refactored the methods to use the callback reference, not the `.name`
**About using `.name`:**
This would only work when the given callback would not be an anonymous function.
Examples:
```js
function normalFn() {}
normalFn.name // normalFn
const arrow = () => {}
arrow.name // arrow
(() => {}).name // empty string
```
In order to identify which callback is which, the function …
> Add off method

- MessageSigning.md
- src/api/extension/index.js
Currently, the MessageSigning.md file contains a signature verification implementation that does not work with CIP-30. This PR updates the documentation to include a solution that works for messages signed with signDataCIP30(...) internally.
This PR also updates the comments on the signDataCIP30 function to clarify why the change was made. Feedback on the comments are welcome.
> Updating Message Signing Verify Documentation

- README.md
While trying to get user's stake address, the error "getRewardAddress is not a function" was returned.
And according to CIP-0030, the correct method name is "getRewardAddresses", which returns an array.
> Readme Fix for "getRewardAddress is not a function" error

- src/ui/app/pages/signData.jsx
- Payload is now splitted into separated lines by line breaks received in the msg data payload. (/r, /r/n, /n)
- increased text area height to fill the blank gap (more room for message data content).
**Example for the change:**
Before:
After:
Raw msg sign data payload used:
```java
String message = "Welcome to adabox.io!\n\n" +
"Click to sign in and accept the Adabox Terms of Service: https://adabox.io/tos\n\n" +
"This request will not trigger a blockchain transaction or cost any fees.\n\n" +
"Your authentication status will reset after 24 hours.\n\n" +
nonceTitle + nonce;
```
> Solves Issue #564: Line Breaks ("\n") isn't supported in Message shown when prompt to sign (signData method) (CIP30).

- src/api/extension/index.js
Given that Blockfrost doesn't currently support version 2 of CIP-25 and instead returns the entire 721 metadata entry, I think a temporary check for this within Nami may be appropriate.
> Test for CIP-25 version 2 in Blockfrost metadata

- src/api/util.js
Currently assets with an empty token name will fail to display in the wallet and cannot be interacted with.
> Fix for assets with empty token names

- src/api/extension/index.js
Previously ada handles were following CIP-25 standards where we can retrieve the owner address by encoding the handle to hex, adding a policy prefix to get the asset ID, and sending a request to Blockfrost.
Now that they have introduced personalization by upgrading your CIP-25 handle to CIP-68, we have handles with both token standards exist. Unfortunately, the old method doesn't work for CIP-68 handles as they have an additional prefix (000de140) before the hex-encoded asset name.
I have replaced the old ```getAdaHandle``` method with the new official API which is more fast and reliable - https://api.handle.me/swagger
You can test the changes by resolving the following handle.
- $neo.ada (CIP-68 Standard)
- $neo.brave (CIP-25 Standard)
Both handles will be resolved by the new official …
> Added support for CIP68 handle

- LICENSE
- NOTICE
- README.md
- package.json
- Replace MIT licence with Apache 2.0, aligning with IOG standards
- Fix link to repository in package.json
- Update docs to indicate IOG as new maintainers
> chore: replace Berry Pool references, update licence to Apache 2.0

- package-lock.json
- src/api/extension/index.js
- src/config/config.js
- src/features/analytics/ui/AnalyticsConsentModal.jsx
- src/features/terms-and-privacy/config.ts
- src/features/terms-and-privacy/hooks.ts
- src/features/terms-and-privacy/index.ts
- src/features/terms-and-privacy/provider.tsx
- src/features/terms-and-privacy/services.ts
- src/features/terms-and-privacy/ui/TermsAndPrivacyModal.jsx
- src/features/terms-and-privacy/ui/TermsAndPrivacyModal.tsx
- src/ui/app/components/about.jsx
- src/ui/app/components/privacyPolicy.jsx
- src/ui/app/components/termsOfUse.jsx
- src/ui/app/pages/welcome.jsx
- src/ui/indexMain.jsx
- Updated terms and conditions and privacy policy.
- Added "terms and policy update" prompt to be displayed for existing installations. 
- If installing nami for the first time, the new terms and policy is displayed as usual in the create/import modal, analytics consent and about screen.
- If wallet is already created, the update modal should be displayed with acceptance prompt
- To retest after accepting, call `chrome.storage.local.remove('acceptedLegalDocsVersion')`
> [LW-9592] Include legal docs

- src/ui/app/components/asset.jsx
- src/ui/app/components/collectible.jsx
- src/ui/app/pages/wallet.jsx
The assetFingerprint function was outdated and it was not passing the props right to the component. 
AssetID: asset1825hfzlnn8fx7yw4we2wny9qv2dkflwf2h8p80 
Cexplorer: https://preprod.cexplorer.io/asset/asset1825hfzlnn8fx7yw4we2wny9qv2dkflwf2h8p80
AssetID: asset1sjk0uucljv4qxxnhq8gjy7r5mar64erhfuh4q8
https://preprod.cexplorer.io/asset/asset1sjk0uucljv4qxxnhq8gjy7r5mar64erhfuh4q8
> Fix - show correct assetID in assets and NFT´s

- src/ui/app/pages/wallet.jsx
It updates the color of the button to be readable in dark UI without changing the light UI.
> FIX: update delegate button color to be readable

- src/api/extension/index.js
- src/api/util.js
Summary: 
The incorrect AssetID was shown in the Send screen and the incorrect one was used to filter the asset in the search input, currently we are displaying the correct AssetId as well as we are able to perform the search with the correct ID .
> [LW-9665] add correct assetId in send screen and search for assets

- .github/workflows/ci.yml
- README.md
This is a corrective action identified during the recent post incident report. The build is now performed as part of the CI workflow, in a more controlled environment, using API keys stored as GitHub repository secrets. See attached workflow run
We'll create a GitHub release next time, so until then the "testnet" README instructions lead to an empty page. Users can access the test networks via the Chrome store version and the prior committed build can be found on earlier revision if needed sooner. 
- Download the build from the CI run and run a few smoke tests.
- Verify the API requests are landing in the Nami account by coordinating with me to check the Blockfrost admin panel.
> ci: replace committed build.zip with Workflow artefact upload

- src/features/analytics/hooks.ts
- src/features/analytics/provider.tsx
- src/features/analytics/ui/AnalyticsConsentModal.jsx
- src/features/settings/legal/LegalSettings.tsx
- src/ui/app/pages/settings.jsx
- src/ui/indexMain.jsx
This PR adds a legal section to the settings screen where analytics can be toggled on/off and Terms of Use + Privacy Policy can be opened. Also other analytics related copy was updated:
> Add legal section to settings LW-9716

- src/api/extension/index.js
Per the recommendation of the pool.pm team and in compliance with metadata standards, we sometimes see NFT IPFS links represented as arrays of strings.  These arrays are meant to be concatenated directly to produce the IPFS link (or data scheme, etc.).
Because the image is retrieved in the send assets page, without this change users are UNABLE to send assets in CIP-68 format (since the decimals do not get properly set in `nami/src/api/extension/index.js#1762`).
[ Testing: npm test, manually built and submitted tx from Nami ]
[ Test Artifacts: txn 5e342b856efa596da433e3eec4256809cfe9bd9c4c9c39eb316328080ced13f1 ]
> fix(NFT Images): Support array image types for CIP-68

- src/ui/app/pages/send.jsx
Fixes LW-9943 and LW-9936
Use local variable inside prepareTx instead of the one inside closure.
> fix: use local variable in prepareTx

- src/ui/app/pages/send.jsx
Users on Twitter have been complaining that when the flint gateway for M1 is not functioning properly it causes them an inability to use the wallet for Cardano mainnet purposes. This obviously shouldn't be the case, so I have added a simple try-catch fix.
> Fix failure to send on Cardano Mainnet.

- src/api/extension/index.js
Nami has an integration with [Milkomeda](https://milkomeda.com/), a Cardano EVM sidechain, that involves making at least two HTTP requests to external service, run by Flint Wallet, in the send form on each load. If this service is not responding, sending funds is blocked, even for users not intending to use the sidechain. The current application design is not resilient to this outage, disabling form fields until a response is received. https://github.com/input-output-hk/nami/pull/880 improved error handling, but to handle hanging requests, a client side timeout is required.
Abort the HTTP requests after 500ms, which should be sufficient time to receive a response without impacting UX.
[Server timing out](https://github.com/input-output-hk/nami/assets/303881/d254ae64-28bb-4e18-9f98-bd03b6e0 …
> fix: timeout http requests to Milkomeda backend

- package-lock.json
- package.json
- src/manifest.json
- src/ui/app/pages/signTx.jsx
The collateral validation logic, in the sign transaction component, is unreasonably expecting explicit collateral to **always** be set **if** there are no UTxOs that have less than 50 Ada. This means if a DApp uses CIP-40 collateral return, and has no suitable UTxOs, an error will be thrown.
If collateral return is found in the transaction body, return from the function to avoid the checks against "account collateral" presence and equality with collateral input.
> fix: collateral check

- package-lock.json
- package.json
- src/api/extension/index.js
- src/api/extension/wallet.js
We still have some reports of input selection failures in wallets with many assets. Nami currently uses CML for input selection, but it seems it doesn't work very well with wallet with many assets. This PR replaces CML with Blaze for wallet built transactions.
> fix: replace CML with Blaze for input selection

- package.json
- src/manifest.json
- src/ui/app/pages/signTx.jsx
See commit message
_These were produced by inverting logic, it's **not** how the pictured DApp behaves_ :grin: 
With both an error (blocking) and warning
> Fix/ warn if collateral return is being directed to another owner

- package-lock.json
- package.json
- src/api/extension/index.js
- src/manifest.json
At some point the Byron address validation stopped working. Given there are no tests, I've just replaced the logic with a tested validator from the `cardano-js-sdk`. It's a minimal change, ignoring the wonky logic of a function named `isValid` returning either the address as a buffer, if valid, or `false`.
Test coverage inherited from:
https://github.com/input-output-hk/cardano-js-sdk/blob/master/packages/core/test/Cardano/Address/Address.test.ts
> fix: replace buggy Cardano address validator

- src/api/extension/wallet.js
- src/ui/app/components/transactionBuilder.jsx
Withdrawals on Nami were failing if the rewards were enough to cover the fees as tx builder was not picking up any extra inputs (transactions without inputs are invalid).
This change makes sure the transaction always spends at least one input.
> fix: withdrawal transaction now always nominate at least one input

- src/ui/app/tabs/hw.jsx
Hardware wallet logic now looks for VID rather than manufacturer string
> fix: hardware wallets are now detected using their VID

- src/ui/app/components/transaction.jsx
implement try/catch with null fallback to prevent nami crashing if `Loader.Cardano.Address.from_bech32(address);` throws due to invalid string length, mixed formatting, or any other issue
[LW-11769](https://input-output.atlassian.net/browse/LW-11769)
> fix: use try/catch with potential unknown address

- .github/workflows/ci.yml
It's currently stored in GitHub as a variable, but it should be a secret. The old key will be rotated in the next release.
> ci: move SENTRY_DSN to GitHub secrets

- src/features/sentry.js
- webpack.config.js
This is producing a massive number of rejected transactions in Sentry. We shouldn't be concerned with the webpage unhandled errors, except for DApp connection errors, which is more challenging to intercept.
> fix: stop injecting Sentry client into content scripts
